import Head from "next/head";
import Image from "next/image";
// React Icons

// Styled-Components
import { GlobalStyle } from "../styles/globals";
import * as Style from "../styles/style";

//Components
import Projeto from "../components/Projeto";
import Tecnologia from "../components/Tecnologia";
import Social from "../components/social";

export default function Home() {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Portifólio Walyson Moura</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Social />
      <Style.Content>
        <Style.Tecnologias>
          <Tecnologia imagem="/html.png" />
          <Tecnologia imagem="/css.png" />
          <Tecnologia imagem="/js.png" />
          <Tecnologia imagem="/type.png" />
          <Tecnologia imagem="/node.png" />
          <Tecnologia imagem="/react.png" />
          <Tecnologia imagem="/next.png" />
        </Style.Tecnologias>

        <Projeto imagem="/exe.png" />
      </Style.Content>
    </>
  );
}
