import Head from "next/head";
import Image from "next/image";

// React Icons

// Styled-Components
import { GlobalStyle } from "../styles/globals";
import * as Style from "../styles/style";

//Components
import Projeto from "../components/Projeto";
import Tecnologia from "../components/Tecnologia";
import Social from "../components/social";

export default function Home() {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Portifólio Walyson Moura</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Social />
      <Style.Main>
        <Style.Principal>
          <div className="apresentacao">
            <h1>Walyson</h1>

            <h2>Engenheiro de software e full stack develop</h2>
          </div>

          <div className="imagens">
            <div className="f1">
              <Image
                src="/css.png"
                width={50}
                height={50}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f2">
              <Image
                src="/html.png"
                width={65}
                height={70}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f3">
              <Image
                style={{ borderRadius: "8px" }}
                src="/type.png"
                width={45}
                height={45}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f4">
              <Image
                style={{ borderRadius: "8px" }}
                src="/type.png"
                width={50}
                height={50}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f5">
              <Image
                src="/node.png"
                width={75}
                height={75}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f6">
              <Image
                src="/react.png"
                width={80}
                height={80}
                alt="imagem"
                responsive
              />
            </div>
            <div className="f7">
              <Image
                src="/next.png"
                width={50}
                height={50}
                alt="imagem"
                responsive
              />
            </div>

            <Image
              style={{ position: "absolute" }}
              src="/walyson2.png"
              width={500}
              height={500}
              alt="imagem"
              responsive
            />
          </div>
        </Style.Principal>
        <Style.Tecnologias>
          <Tecnologia imagem="/html.png" />
          <Tecnologia imagem="/css.png" />
          <Tecnologia imagem="/js.png" />
          <Tecnologia imagem="/type.png" />
          <Tecnologia imagem="/node.png" />
          <Tecnologia imagem="/react.png" />
          <Tecnologia imagem="/next.png" />
        </Style.Tecnologias>

        <Projeto imagem="/exe.png" />
      </Style.Main>
    </>
  );
}
